import type { SubtitleItem } from '../../core/models/SubtitleItem'
import type { AssStyle } from '../../core/models/AssStyle'
import { createDefaultStyle } from '../../core/models/AssStyle'
import { srtTimeToMs, msToAssTime } from '../../utils/time'

/**
 * Convert SRT subtitle content to ASS format
 * @param content SRT file content
 * @param styles Optional custom styles to use
 * @returns ASS formatted string
 */
export function srtToAss(content: string, styles?: AssStyle[]): string {
  const items = parseSrtContent(content)
  const defaultStyle = createDefaultStyle()
  const usedStyles = styles?.length ? styles : [defaultStyle]

  return generateAssFile(items, usedStyles)
}

/**
 * Parse SRT content to subtitle items
 */
function parseSrtContent(content: string): SubtitleItem[] {
  const items: SubtitleItem[] = []
  const blocks = content.split(/\r?\n\s*\r?\n/)

  for (const block of blocks) {
    const trimmed = block.trim()
    if (!trimmed) continue

    const item = parseSrtBlock(trimmed)
    if (item) {
      items.push(item)
    }
  }

  return items
}

/**
 * Parse a single SRT block
 */
function parseSrtBlock(block: string): SubtitleItem | null {
  const lines = block.split(/\r?\n/)

  if (lines.length < 2) {
    return null
  }

  // Find the time line (contains -->)
  let timeLineIndex = -1
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes('-->')) {
      timeLineIndex = i
      break
    }
  }

  if (timeLineIndex === -1) {
    return null
  }

  const timeLine = lines[timeLineIndex]
  const textLines = lines.slice(timeLineIndex + 1)

  // Parse time: "00:00:01,000 --> 00:00:04,000"
  const timeMatch = timeLine.match(
    /^\s*(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/
  )

  if (!timeMatch) {
    return null
  }

  try {
    const startTime = srtTimeToMs(timeMatch[1])
    const endTime = srtTimeToMs(timeMatch[2])

    const text = textLines
      .join('\n')
      .replace(/<[^>]+>/g, '') // Remove HTML tags
      .trim()

    if (!text) {
      return null
    }

    return {
      id: `srt-${startTime}-${Date.now()}`,
      startTime,
      endTime,
      text,
    }
  } catch (e) {
    console.error('Failed to parse SRT block:', block, e)
    return null
  }
}

/**
 * Generate ASS file content
 */
function generateAssFile(items: SubtitleItem[], styles: AssStyle[]): string {
  const lines: string[] = []

  // Script Info section
  lines.push('[Script Info]')
  lines.push('; Script generated by SubtitleShop')
  lines.push('Title: Converted from SRT')
  lines.push('ScriptType: v4.00+')
  lines.push('Collisions: Normal')
  lines.push('PlayDepth: 0')
  lines.push('')

  // V4+ Styles section
  lines.push('[V4+ Styles]')
  lines.push(
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding'
  )

  for (const style of styles) {
    lines.push(serializeStyle(style))
  }

  lines.push('')

  // Events section
  lines.push('[Events]')
  lines.push('Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text')

  for (let i = 0; i < items.length; i++) {
    const item = items[i]
    const line = serializeDialogue(item, i, styles[0]?.name || 'Default')
    if (line) lines.push(line)
  }

  return lines.join('\n')
}

/**
 * Serialize an ASS style to string
 */
function serializeStyle(style: AssStyle): string {
  const fields = [
    style.name,
    style.fontName,
    style.fontSize.toString(),
    style.primaryColor,
    style.secondaryColor,
    style.outlineColor,
    style.backColor,
    style.bold ? '-1' : '0',
    style.italic ? '-1' : '0',
    style.underline ? '-1' : '0',
    style.strikeOut ? '-1' : '0',
    style.scaleX.toString(),
    style.scaleY.toString(),
    style.spacing.toString(),
    style.angle.toString(),
    style.borderStyle.toString(),
    style.outline.toString(),
    style.shadow.toString(),
    style.alignment.toString(),
    style.marginL.toString(),
    style.marginR.toString(),
    style.marginV.toString(),
    style.encoding.toString(),
  ]
  return `Style: ${fields.join(', ')}`
}

/**
 * Serialize a dialogue line to ASS format
 */
function serializeDialogue(
  item: SubtitleItem,
  layer: number,
  styleName: string
): string | null {
  if (item.startTime >= item.endTime) {
    return null
  }

  // Convert newlines to \N for ASS format
  const text = item.text.replace(/\n/g, '\\N')

  const fields = [
    layer.toString(),
    msToAssTime(item.startTime),
    msToAssTime(item.endTime),
    styleName,
    '', // Name
    '0', // MarginL
    '0', // MarginR
    '0', // MarginV
    '', // Effect
    text,
  ]

  return `Dialogue: ${fields.join(',')}`
}
